---
name: Tests and Checks
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: [
            '22.0', '22.1', '22.2', '22.3', 
            '23.0', '23.1', '23.2', '23.3', 
            '24.0', '24.1', '24.2', '24.3',
            '25.0', '25.1'
        ]
        rebar3_vsn: ['3.18', '3.19']
        os: [ubuntu-latest]
        exclude:
          # rebar 3.19
          - rebar3_vsn: '3.19'
            otp_vsn: '22.0'
          - rebar3_vsn: '3.19'
            otp_vsn: '22.1'
          - rebar3_vsn: '3.19'
            otp_vsn: '22.2'
          - rebar3_vsn: '3.19'
            otp_vsn: '22.3'

          # rebar 3.18
          - rebar3_vsn: '3.18'
            otp_vsn: '23.0'
          - rebar3_vsn: '3.18'
            otp_vsn: '23.1'
          - rebar3_vsn: '3.18'
            otp_vsn: '23.2'
          - rebar3_vsn: '3.18'
            otp_vsn: '23.3'
          #
          - rebar3_vsn: '3.18'
            otp_vsn: '24.0'
          - rebar3_vsn: '3.18'
            otp_vsn: '24.1'
          - rebar3_vsn: '3.18'
            otp_vsn: '24.2'
          - rebar3_vsn: '3.18'
            otp_vsn: '24.3'
          #
          - rebar3_vsn: '3.18'
            otp_vsn: '25.0'
          - rebar3_vsn: '3.18'
            otp_vsn: '25.1'
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: ${{matrix.rebar3_vsn}}
      - name: restore _build
        uses: actions/cache@v2
        with:
          path: _build
          key: _build-cache-for-os-${{runner.os}}-otp-${{steps.setup-beam.outputs.otp-version}}-rebar3-${{steps.setup-beam.outputs.rebar3-version}}-hash-${{hashFiles('rebar.lock')}}
      - name: restore rebar3's cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3
          key: rebar3-cache-for-os-${{runner.os}}-otp-${{steps.setup-beam.outputs.otp-version}}-rebar3-${{steps.setup-beam.outputs.rebar3-version}}-hash-${{hashFiles('rebar.lock')}}
      - run: make test check
